opentelemetry/exception/ext/__init__.py,sha256=YiMOoIzwTkfUIHeikHJJ8WMewsE2jDO986Rec7qOTAI,219
opentelemetry/exception/ext/_internal/exception_recorder.py,sha256=enfEjv-5CHw7lQkGA-gfg-vsYqephL1LU8Dj12rIxlQ,5444
opentelemetry_exception_ext-0.0.4.dist-info/METADATA,sha256=8lEgPNf5eqF5fEpYYANZeWUUfIVm1EZGh7gwAJH4FSU,2844
opentelemetry_exception_ext-0.0.4.dist-info/WHEEL,sha256=9QBuHhg6FNW7lppboF2vKVbCGTVzsFykgRQjjlajrhA,87
opentelemetry_exception_ext-0.0.4.dist-info/licenses/LICENSE,sha256=pRySM7W-ZKH9rftylyt_BAsvwL9ScBSZ-8bP4Mz_ZZE,1068
opentelemetry_exception_ext-0.0.4.dist-info/RECORD,,
